# prox Bash integration, generated by `prox init bash`.
# This file is embedded in the prox binary. Do not source it directly from an
# installed source tree; evaluate the output of `prox init bash` instead.

if (( BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 3) )); then
    printf 'prox: Bash 4.3 or newer is required\n' >&2
else
    if [[ -z ${__PROX_HOOK_VERSION+x} ]]; then
        declare -g __PROX_ACTIVE=0
        declare -g __PROX_PROXY_DISPLAY=''
        declare -gA __PROX_SAVED_SET=()
        declare -gA __PROX_SAVED_VALUE=()
        declare -gA __PROX_SAVED_EXPORTED=()
        declare -gA __PROX_EXPECTED_VALUE=()
    fi

    declare -g __PROX_HOOK_VERSION='@VERSION@'
    declare -ga __PROX_MANAGED_VARIABLES=(
        http_proxy
        https_proxy
        all_proxy
        HTTPS_PROXY
        ALL_PROXY
        no_proxy
        NO_PROXY
    )

    _prox_snapshot_environment() {
        local name declaration
        __PROX_SAVED_SET=()
        __PROX_SAVED_VALUE=()
        __PROX_SAVED_EXPORTED=()
        __PROX_EXPECTED_VALUE=()

        for name in "${__PROX_MANAGED_VARIABLES[@]}"; do
            if [[ -v "$name" ]]; then
                __PROX_SAVED_SET["$name"]=1
                __PROX_SAVED_VALUE["$name"]="${!name}"
                declaration="$(declare -p "$name" 2>/dev/null)"
                if [[ "$declaration" == declare\ -x* ]]; then
                    __PROX_SAVED_EXPORTED["$name"]=1
                else
                    __PROX_SAVED_EXPORTED["$name"]=0
                fi
            else
                __PROX_SAVED_SET["$name"]=0
                __PROX_SAVED_EXPORTED["$name"]=0
            fi
        done
    }

    _prox_restore_environment() {
        local name
        for name in "${__PROX_MANAGED_VARIABLES[@]}"; do
            if [[ ${__PROX_SAVED_SET["$name"]:-0} == 1 ]]; then
                printf -v "$name" '%s' "${__PROX_SAVED_VALUE["$name"]}"
                if [[ ${__PROX_SAVED_EXPORTED["$name"]:-0} == 1 ]]; then
                    export "$name"
                else
                    export -n "$name" 2>/dev/null || true
                fi
            else
                unset "$name"
            fi
        done

        __PROX_ACTIVE=0
        __PROX_PROXY_DISPLAY=''
        __PROX_SAVED_SET=()
        __PROX_SAVED_VALUE=()
        __PROX_SAVED_EXPORTED=()
        __PROX_EXPECTED_VALUE=()
    }

    _prox_environment_drifted() {
        local name
        for name in "${__PROX_MANAGED_VARIABLES[@]}"; do
            if [[ ! -v "$name" ]]; then
                return 0
            fi
            if [[ "${!name}" != "${__PROX_EXPECTED_VALUE["$name"]}" ]]; then
                return 0
            fi
        done
        return 1
    }

    _prox_on() {
        local -a global_options=()
        while (( $# > 0 )) && [[ $1 != -- ]]; do
            global_options+=("$1")
            shift
        done
        if (( $# > 0 )); then
            shift
        fi
        if (( $# != 0 )); then
            printf 'prox: V0.1 does not accept arguments for `prox on`\n' >&2
            return 2
        fi

        if [[ $__PROX_ACTIVE == 1 ]]; then
            if _prox_environment_drifted; then
                printf 'prox: managed proxy variables changed after activation\n' >&2
                printf 'Run `prox off` before enabling prox again.\n' >&2
                return 1
            fi
            printf 'Proxy is already enabled: %s\n' "$__PROX_PROXY_DISPLAY"
            return 0
        fi

        local generated name status
        generated="$(command prox "${global_options[@]}" __shell-env bash)"
        status=$?
        if (( status != 0 )); then
            return "$status"
        fi

        _prox_snapshot_environment
        if ! eval "$generated"; then
            _prox_restore_environment
            printf 'prox: failed to update the current Shell environment\n' >&2
            return 1
        fi

        for name in "${__PROX_MANAGED_VARIABLES[@]}"; do
            __PROX_EXPECTED_VALUE["$name"]="${!name}"
        done
        __PROX_ACTIVE=1
        printf 'Proxy enabled: %s\n' "$__PROX_PROXY_DISPLAY"
    }

    _prox_off() {
        if (( $# != 0 )); then
            printf 'prox: V0.1 does not accept arguments for `prox off`\n' >&2
            return 2
        fi
        if [[ $__PROX_ACTIVE != 1 ]]; then
            printf 'Proxy is already disabled.\n'
            return 0
        fi

        if _prox_environment_drifted; then
            printf 'Warning: managed proxy variables changed after activation.\n' >&2
        fi
        _prox_restore_environment
        printf 'Proxy disabled. Previous environment restored.\n'
    }

    _prox_status() {
        local -a global_options=()
        while (( $# > 0 )) && [[ $1 != -- ]]; do
            global_options+=("$1")
            shift
        done
        if (( $# > 0 )); then
            shift
        fi
        local state='inactive'
        if [[ $__PROX_ACTIVE == 1 ]]; then
            state='active'
            if _prox_environment_drifted; then
                state='drifted'
            fi
        fi

        PROX_INTERNAL_STATE="$state" \
        PROX_INTERNAL_PROXY="$__PROX_PROXY_DISPLAY" \
            command prox "${global_options[@]}" status "$@"
    }

    prox() {
        if (( $# == 0 )); then
            command prox help
            return $?
        fi

        local -a global_options=()
        while (( $# > 0 )); do
            case "$1" in
                --config)
                    if (( $# < 2 )) || [[ -z $2 ]]; then
                        printf 'prox: --config requires a path\n' >&2
                        return 2
                    fi
                    global_options+=("$1" "$2")
                    shift 2
                    ;;
                --config=*)
                    if [[ $1 == --config= ]]; then
                        printf 'prox: --config requires a path\n' >&2
                        return 2
                    fi
                    global_options+=("$1")
                    shift
                    ;;
                *)
                    break
                    ;;
            esac
        done

        if (( $# == 0 )); then
            command prox "${global_options[@]}"
            return $?
        fi

        local subcommand="$1"
        shift
        case "$subcommand" in
            on)
                _prox_on "${global_options[@]}" -- "$@"
                ;;
            off)
                _prox_off "$@"
                ;;
            status)
                _prox_status "${global_options[@]}" -- "$@"
                ;;
            *)
                command prox "${global_options[@]}" "$subcommand" "$@"
                ;;
        esac
    }
fi
